services:
  db:
    image: pgvector/pgvector:pg16
    container_name: study_chatbot
    env_file: .env
    ports:
      - "5432:5432"
    volumes:
      - ./data/postgres:/var/lib/postgresql/data

  app:
    build: ./back-end
    container_name: chatbot_app
    env_file: .env
    ports:
      - "8000:8000"
    volumes:
      - ./back-end:/app
      - ./front-end:/front-end
    depends_on:
      - db